name = "vibecode-starter-kit"
compatibility_date = "2024-10-22"
pages_build_output_dir = "dist"

# Cloudflare Pages specific configuration
[build]
command = "bun run build"

# Environment variables example
# [vars]
# MY_VAR = "my-value"

# Secrets should be set via the Cloudflare dashboard or wrangler secret
# wrangler secret put MY_SECRET